# Generated by Django 5.1.1 on 2024-09-20 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='дата добавления')),
                ('data_now', models.DateField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=50, verbose_name='названия')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='дата добавления')),
                ('data_now', models.DateField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=50, verbose_name='названия')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='дата добавления')),
                ('data_now', models.DateField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=35, verbose_name='название')),
                ('decrypt', models.CharField(max_length=100, verbose_name='описания')),
                ('content', models.TextField(verbose_name='Контент')),
                ('is_public', models.BooleanField(default=True, verbose_name='публичный')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='news.category')),
                ('tags', models.ManyToManyField(related_name='tags', to='news.tag', verbose_name='Теги')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
